=== AlexRodwell/netrunner-cards-json/schema/v2/card_pool_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/card_pool_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "code": {
        "minLength": 1,
        "type": "string"
      },
      "name": {
        "minLength": 1,
        "type": "string"
      },
      "cycles": {
        "type": "array",
        "items": {
          "minLength": 1,
          "type": "string"
        }
      },
      "packs": {
        "type": "array",
        "items": {
          "minLength": 1,
          "type": "string"
        }
      }
    },
    "required": ["code", "name"]
  }
}

=== AlexRodwell/netrunner-cards-json/card_pools/snapshot.json
[
  {
    "code": "snapshot",
    "name": "Snapshot",
    "cycles": ["lunar", "sansan", "mumbad", "flashpoint", "red_sand", "kitara"],
    "packs": ["cac", "hap", "oac", "td", "core2", "rar"]
  },
  {
    "code": "snapshot_plus",
    "name": "Snapshot+",
    "cycles": ["lunar", "sansan", "mumbad", "flashpoint", "red_sand", "kitara"],
    "packs": ["cac", "hap", "oac", "td", "core2", "rar", "mo"]
  }
]
