=== AlexRodwell/netrunner-cards-json/schema/v2/printings_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/printings_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "card_id": {
        "minLength": 1,
        "type": "string"
      },
      "card_set_id": {
        "minLength": 1,
        "type": "string"
      },
      "flavor": {
        "minLength": 1,
        "type": "string"
      },
      "id": {
        "minLength": 1,
        "type": "string"
      },
      "illustrator": {
        "minLength": 1,
        "type": "string"
      },
      "position": {
        "minimum": 1,
        "type": "integer"
      },
      "printed_is_unique": {
        "type": "boolean"
      },
      "printed_text": {
        "type": "string"
      },
      "quantity": {
        "minimum": 1,
        "type": "integer"
      },
      "stripped_printed_text": {
        "type": "string"
      }
    },
    "required": [
      "card_id",
      "card_set_id",
      "id",
      "position",
      "printed_is_unique",
      "quantity"
    ]
  }
}

=== AlexRodwell/netrunner-cards-json/v2/printings/future_proof.json
[
  {
    "card_id": "retrieval_run",
    "card_set_id": "future_proof",
    "id": "02101",
    "illustrator": "Outland Entertainment LLC",
    "position": 101,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "darwin",
    "card_set_id": "future_proof",
    "id": "02102",
    "illustrator": "Liiga Smilshkalne",
    "position": 102,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "data_leak_reversal",
    "card_set_id": "future_proof",
    "flavor": "A two-way solution to a one-way problem, the data leak reversal, or DLR for short, is a misnomer. There is no actual reversal of data, only the creation of a parallel peer-to-peer link with the initial source.",
    "id": "02103",
    "illustrator": "Andrew Mar",
    "position": 103,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "faerie",
    "card_set_id": "future_proof",
    "flavor": "Do you believe in faeries?",
    "id": "02104",
    "illustrator": "Sara K. Diesel",
    "position": 104,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "mr_li",
    "card_set_id": "future_proof",
    "flavor": "\"We're always happy to help, Mr. Santiago.\"\n\"I appreciate it, Mr. Li.\"\n\"We'll be in touch. And, Gabriel…\"\n\"Yes?\"\n\"Don't leave town.\"",
    "id": "02105",
    "illustrator": "Gong Studios",
    "position": 105,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "indexing",
    "card_set_id": "future_proof",
    "flavor": "A little corporate restructuring is necessary once in a while.",
    "id": "02106",
    "illustrator": "Mauricio Herrera",
    "position": 106,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "r_d_interface",
    "card_set_id": "future_proof",
    "flavor": "Works best at your own desk.",
    "id": "02107",
    "illustrator": "Reza Ilyasa",
    "position": 107,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "deep_thought",
    "card_set_id": "future_proof",
    "id": "02108",
    "illustrator": "Anna Ignatieva",
    "position": 108,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "new_angeles_city_hall",
    "card_set_id": "future_proof",
    "flavor": "\"New Angeles is the jewel of modern civilization, and its government the envy of nations.\" -Mayor Wells",
    "id": "02109",
    "illustrator": "Henning Ludvigsen",
    "position": 109,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "eli_1_0",
    "card_set_id": "future_proof",
    "flavor": "\"That's against the rules. The Creators will be angry.\"",
    "id": "02110",
    "illustrator": "Sandara Tang",
    "position": 110,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "ruhr_valley",
    "card_set_id": "future_proof",
    "flavor": "Known for luxury hoppers and a delectable sauerkraut.",
    "id": "02111",
    "illustrator": "Yoann Boissonnet",
    "position": 111,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "ronin",
    "card_set_id": "future_proof",
    "flavor": "\"I will serve you…for a time.\"",
    "id": "02112",
    "illustrator": "Adam S. Doyle",
    "position": 112,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "midori",
    "card_set_id": "future_proof",
    "flavor": "\"Looks like someone is being naughty…\"",
    "id": "02113",
    "illustrator": "RJ Palmer",
    "position": 113,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "nbn_the_world_is_yours",
    "card_set_id": "future_proof",
    "flavor": "*Some restrictions may apply. Scan this card to find out more.",
    "id": "02114",
    "position": 114,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "project_beale",
    "card_set_id": "future_proof",
    "id": "02115",
    "illustrator": "Matt Zeilinger",
    "position": 115,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "midseason_replacements",
    "card_set_id": "future_proof",
    "id": "02116",
    "illustrator": "Christina Davis",
    "position": 116,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "flare",
    "card_set_id": "future_proof",
    "flavor": "A bright light blossomed, and then the console went dark. That's when she smelled smoke.",
    "id": "02117",
    "illustrator": "Mike Nesbitt",
    "position": 117,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "dedicated_response_team",
    "card_set_id": "future_proof",
    "flavor": "They don't call them dedicated for nothing.",
    "id": "02118",
    "illustrator": "Reza Ilyasa",
    "position": 118,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "burke_bugs",
    "card_set_id": "future_proof",
    "flavor": "\"If I had to describe the bugs in one word, it would be '****ing annoying.'\" -Whizzard",
    "id": "02119",
    "illustrator": "Reza Ilyasa",
    "position": 119,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "corporate_war",
    "card_set_id": "future_proof",
    "flavor": "There were several ways to win a corporate war. One of them was to bring out the bazookas.",
    "id": "02120",
    "illustrator": "Gong Studios",
    "position": 120,
    "printed_is_unique": false,
    "quantity": 3
  }
]

=== AlexRodwell/netrunner-cards-json/v2/printings/blood_money.json
[
  {
    "card_id": "credit_crash",
    "card_set_id": "blood_money",
    "id": "11021",
    "illustrator": "Jenn Tran",
    "position": 21,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "rumor_mill",
    "card_set_id": "blood_money",
    "flavor": "\"You can have a lot of fun in 23 seconds.\" -Princess Space Kitten",
    "id": "11022",
    "illustrator": "Tim Durning",
    "position": 22,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "nfr",
    "card_set_id": "blood_money",
    "flavor": "Balance out the equation.",
    "id": "11023",
    "illustrator": "Mariusz Siergiejew",
    "position": 23,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "paperclip",
    "card_set_id": "blood_money",
    "flavor": "\"It is not wise to call someone crazy until you fully understand what they're trying to say.\" -Omar Keung",
    "id": "11024",
    "illustrator": "Adam S. Doyle",
    "position": 24,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "golden",
    "card_set_id": "blood_money",
    "flavor": "The program was as close to a hunting raptor as she could afford...for now.",
    "id": "11025",
    "illustrator": "Liiga Smilshkalne",
    "position": 25,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "temujin_contract",
    "card_set_id": "blood_money",
    "flavor": "\"The best part is, it's legal!\" -Khan",
    "id": "11026",
    "illustrator": "Timur Shevtsov",
    "position": 26,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "khan_savvy_skiptracer",
    "card_set_id": "blood_money",
    "id": "11027",
    "illustrator": "Matt Zeilinger",
    "position": 27,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "data_breach",
    "card_set_id": "blood_money",
    "flavor": "Once a security flaw is identified, there's only a limited window to exploit it before it's patched. Runners call this period \"open season.\"",
    "id": "11028",
    "illustrator": "Juan Novelletto",
    "position": 28,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "algo_trading",
    "card_set_id": "blood_money",
    "id": "11029",
    "illustrator": "Caroline Elizabeth Huss",
    "position": 29,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "beth_kilrain_chang",
    "card_set_id": "blood_money",
    "flavor": "\"Coming to you live from the front lines, for now, unless they kill me...\"",
    "id": "11030",
    "illustrator": "Aurore Folny",
    "position": 30,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "fairchild_2_0",
    "card_set_id": "blood_money",
    "flavor": "To threaten my treasures is to incur my wrath.",
    "id": "11031",
    "illustrator": "Liiga Smilshkalne",
    "position": 31,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "aiki",
    "card_set_id": "blood_money",
    "flavor": "First, blend with the attacker. Then, control the attack.",
    "id": "11032",
    "illustrator": "BalanceSheet",
    "position": 32,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "enforcing_loyalty",
    "card_set_id": "blood_money",
    "flavor": "\"Eiko here. It's done.\"",
    "id": "11033",
    "illustrator": "Adam Schumpert",
    "position": 33,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "hatchet_job",
    "card_set_id": "blood_money",
    "flavor": "\"SELL!! Buy platinum, but GET OUT OF THE TT CREDIT! It is TOXIC!\"",
    "id": "11034",
    "illustrator": "Gary Bedell",
    "position": 34,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "special_report",
    "card_set_id": "blood_money",
    "flavor": "By the time the report of Emelyov's murder was produced, there had already been a dozen more, hitting all the corps.",
    "id": "11035",
    "illustrator": "Aurore Folny",
    "position": 35,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "c_i_fund",
    "card_set_id": "blood_money",
    "id": "11036",
    "illustrator": "Samuel Leung",
    "position": 36,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "liquidation",
    "card_set_id": "blood_money",
    "flavor": "What's a little insurance fraud between friends?",
    "id": "11037",
    "illustrator": "Pavel Kolomeyets",
    "position": 37,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "weyland_consortium_builder_of_nations",
    "card_set_id": "blood_money",
    "flavor": "Strength makes leaders.",
    "id": "11038",
    "position": 38,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "financial_collapse",
    "card_set_id": "blood_money",
    "flavor": "She'd never heard her dads argue like this. Not ever. She'd give anything to make it stop.",
    "id": "11039",
    "illustrator": "Matt Zeilinger",
    "position": 39,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "prisec",
    "card_set_id": "blood_money",
    "flavor": "\"While the money pooled at the top, the power went with it, until there were two sets of laws: one for them, one for us\" -Omar Keung, the Flashpoint",
    "id": "11040",
    "illustrator": "Maciej Rebisz",
    "position": 40,
    "printed_is_unique": false,
    "quantity": 3
  }
]

=== AlexRodwell/netrunner-cards-json/v2/printings/the_spaces_between.json
[
  {
    "card_id": "the_foundry_refining_the_process",
    "card_set_id": "the_spaces_between",
    "id": "06021",
    "illustrator": "Emilio Rodriguez",
    "position": 21,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "enhanced_login_protocol",
    "card_set_id": "the_spaces_between",
    "id": "06022",
    "illustrator": "Lili Ibrahim",
    "position": 22,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "heinlein_grid",
    "card_set_id": "the_spaces_between",
    "flavor": "\"There are many advantages to having facilities on the moon. Less traffic, for example.\" -Director Hass",
    "id": "06023",
    "illustrator": "Henning Ludvigsen",
    "position": 23,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "encrypted_portals",
    "card_set_id": "the_spaces_between",
    "flavor": "\"Binary computing is obsolete. I use a base-4 structure for this system; it's modeled on our DNA. Well, my DNA, anyway.\" -Doctor Endo, Jinteki researcher",
    "id": "06024",
    "illustrator": "Adam S. Doyle",
    "position": 24,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "cerebral_static",
    "card_set_id": "the_spaces_between",
    "flavor": "Her eyes were the color of a vidscreen, tuned to a dead channel.",
    "id": "06025",
    "illustrator": "Lili Ibrahim",
    "position": 25,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "targeted_marketing",
    "card_set_id": "the_spaces_between",
    "id": "06026",
    "illustrator": "Gong Studios",
    "position": 26,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "information_overload",
    "card_set_id": "the_spaces_between",
    "flavor": "Throw enough data at a runner and it ceases to have any meaning at all.",
    "id": "06027",
    "illustrator": "Ed Mattinian",
    "position": 27,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "paywall_implementation",
    "card_set_id": "the_spaces_between",
    "id": "06028",
    "illustrator": "Gong Studios",
    "position": 28,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "sealed_vault",
    "card_set_id": "the_spaces_between",
    "flavor": "Nothing is impenetrable. The key is to make breaking into it more costly than what it's worth.",
    "id": "06029",
    "illustrator": "Bruno Balixa",
    "position": 29,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "eden_fragment",
    "card_set_id": "the_spaces_between",
    "id": "06030",
    "illustrator": "Seage",
    "position": 30,
    "printed_is_unique": true,
    "quantity": 3
  },
  {
    "card_id": "lag_time",
    "card_set_id": "the_spaces_between",
    "flavor": "\"I don't care how good your console is, or how tricked out your rig is. The lag time on a run on the moon from earthside can be a killer.\" -Leela Patel",
    "id": "06031",
    "illustrator": "Ed Mattinian",
    "position": 31,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "will_o_the_wisp",
    "card_set_id": "the_spaces_between",
    "id": "06032",
    "illustrator": "Adam S. Doyle",
    "position": 32,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "d4v1d",
    "card_set_id": "the_spaces_between",
    "flavor": "Sometimes a single stone is enough.",
    "id": "06033",
    "illustrator": "Andreas Zafiratos",
    "position": 33,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "scrubbed",
    "card_set_id": "the_spaces_between",
    "id": "06034",
    "illustrator": "Chris Newman",
    "position": 34,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "three_steps_ahead",
    "card_set_id": "the_spaces_between",
    "flavor": "In this business, you had to anticipate. If you weren't three steps ahead, you were three steps behind.",
    "id": "06035",
    "illustrator": "Beny Maulana",
    "position": 35,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "unscheduled_maintenance",
    "card_set_id": "the_spaces_between",
    "flavor": "What goes up must always go down.",
    "id": "06036",
    "illustrator": "Aaron Agregado",
    "position": 36,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "cache",
    "card_set_id": "the_spaces_between",
    "flavor": "\"People keep saying that 'Cash is king' in the business, like it's untraceable in the days of DNA sniffers and microtracers. Digital credits can be just as anonymous, and they're just as easy to counterfeit.\" -Silhouette",
    "id": "06037",
    "illustrator": "Ed Mattinian",
    "position": 37,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "net_celebrity",
    "card_set_id": "the_spaces_between",
    "flavor": "Fifteen seconds of fame.",
    "id": "06038",
    "illustrator": "Isuardi Therianto",
    "position": 38,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "llds_energy_regulator",
    "card_set_id": "the_spaces_between",
    "flavor": "Originally not very popular, the regulator was overlooked by those who used energy sinks to protect their rig. But it quickly found an audience once Smoke casted a run on a Blue Sun server, using it to keep her rig online while repeatedly diverting energy spikes in excess of 50,000 volts.",
    "id": "06039",
    "illustrator": "Ed Mattinian",
    "position": 39,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "ghost_runner",
    "card_set_id": "the_spaces_between",
    "flavor": "In the spaces between the data, do trapped souls from the past persist?",
    "id": "06040",
    "illustrator": "Madeline Boni",
    "position": 40,
    "printed_is_unique": false,
    "quantity": 3
  }
]

=== AlexRodwell/netrunner-cards-json/v2/printings/trace_amount.json
[
  {
    "card_id": "vamp",
    "card_set_id": "trace_amount",
    "flavor": "There was a certain schadenfreude about throwing away your credits.",
    "id": "02021",
    "illustrator": "Ed Mattinian",
    "position": 21,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "liberated_account",
    "card_set_id": "trace_amount",
    "flavor": "It's easier to spend when it's not your money.",
    "id": "02022",
    "illustrator": "Matt Zeilinger",
    "position": 22,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "satellite_uplink",
    "card_set_id": "trace_amount",
    "flavor": "T-minus 13 seconds. Leela had to work fast. She jacked in the mesa wire and activated the screen. 7 seconds. The internal SLD was still booting. 4 seconds. The interface flickered to life with an orange glow. 2 seconds. With a tap of a finger she was in.",
    "id": "02023",
    "illustrator": "Matt Zeilinger",
    "position": 23,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "e3_feedback_implants",
    "card_set_id": "trace_amount",
    "flavor": "CyberSolutions' e3 line of implants trade strictly in muscle memory and autonomic responses, freeing the brain to focus entirely on cerebral tasks.",
    "id": "02024",
    "illustrator": "Mauricio Herrera",
    "position": 24,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "compromised_employee",
    "card_set_id": "trace_amount",
    "id": "02025",
    "illustrator": "Mitchell Malloy",
    "position": 25,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "notoriety",
    "card_set_id": "trace_amount",
    "flavor": "When you're this good, it's hard not to grow a fan base.",
    "id": "02026",
    "illustrator": "Matt Zeilinger",
    "position": 26,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "snowball",
    "card_set_id": "trace_amount",
    "flavor": "\"If your snowball gets big enough, you can make it into a snowman!\" -Chaos Theory",
    "id": "02027",
    "illustrator": "Adam S. Doyle",
    "position": 27,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "dyson_mem_chip",
    "card_set_id": "trace_amount",
    "flavor": "Archaic but reliable.",
    "id": "02028",
    "illustrator": "JB Casacop",
    "position": 28,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "encryption_protocol",
    "card_set_id": "trace_amount",
    "flavor": "The key to the future lies in the past.",
    "id": "02029",
    "illustrator": "Adam S. Doyle",
    "position": 29,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "sherlock_1_0",
    "card_set_id": "trace_amount",
    "id": "02030",
    "illustrator": "Matt Zeilinger",
    "position": 30,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "jinteki_replicating_perfection",
    "card_set_id": "trace_amount",
    "id": "02031",
    "position": 31,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "fetal_ai",
    "card_set_id": "trace_amount",
    "id": "02032",
    "illustrator": "Eko Puteh",
    "position": 32,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "trick_of_light",
    "card_set_id": "trace_amount",
    "flavor": "Smoke and mirrors optional.",
    "id": "02033",
    "illustrator": "Anna Ignatieva",
    "position": 33,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "sensei",
    "card_set_id": "trace_amount",
    "flavor": "Peace and violence. Both must lead to the same place.",
    "id": "02034",
    "illustrator": "Sandara Tang",
    "position": 34,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "big_brother",
    "card_set_id": "trace_amount",
    "flavor": "Looking out for your interests since 1984.",
    "id": "02035",
    "illustrator": "Matt Zeilinger",
    "position": 35,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "chilo_city_grid",
    "card_set_id": "trace_amount",
    "flavor": "Clones whisper of ChiLo as a promised land of freedom.",
    "id": "02036",
    "illustrator": "Jonathan Lee",
    "position": 36,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "power_grid_overload",
    "card_set_id": "trace_amount",
    "id": "02037",
    "illustrator": "Howard Schechlman",
    "position": 37,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "amazon_industrial_zone",
    "card_set_id": "trace_amount",
    "id": "02038",
    "illustrator": "Jon Hrubesch",
    "position": 38,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "executive_retreat",
    "card_set_id": "trace_amount",
    "id": "02039",
    "illustrator": "JB Casacop",
    "position": 39,
    "printed_is_unique": false,
    "quantity": 3
  },
  {
    "card_id": "freelancer",
    "card_set_id": "trace_amount",
    "flavor": "No contract. Just a handshake and a fistful of C-6 high explosives.",
    "id": "02040",
    "illustrator": "RJ Palmer",
    "position": 40,
    "printed_is_unique": false,
    "quantity": 3
  }
]

=== AlexRodwell/netrunner-cards-json/v2/printings/ms.json
[
  {
    "card_id": "pinhole_threading",
    "card_set_id": "ms",
    "flavor": "NeneciÄŸim would be proud.",
    "id": "33013",
    "illustrator": "Bruno Balixa",
    "position": 13,
    "printed_is_unique": false,
    "printed_text": "Run any server. If successful, instead of breaching the attacked server, access 1 card in the root of another server. If that card is an agenda, you cannot steal or trash it during this access.",
    "quantity": 3,
    "stripped_printed_text": "Run any server. If successful, instead of breaching the attacked server, access 1 card in the root of another server. If that card is an agenda, you cannot steal or trash it during this access."
  }
]
