=== AlexRodwell/netrunner-cards-json/schema/v2/restriction_schema.json
{
  "$id": "https://github.com/netrunnerdb/netrunner-cards-json/blob/master/schema/v2/restriction_schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "minLength": 1,
      "type": "string"
    },
    "banned": {
      "type": "array",
      "items": {
        "minLength": 1,
        "type": "string"
      }
    },
    "date_start": {
      "minLength": 1,
      "type": "string"
    },
    "subtypes": {
      "type": "object",
      "properties": {
        "banned": {
          "type": "array",
          "items": {
            "minLength": 1,
            "type": "string"
          }
        }
      }
    },
    "global_penalty": {
      "type": "object",
      "properties": {
        "1": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "universal_faction_cost": {
      "type": "object",
      "properties": {
        "1": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "3": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "points": {
      "type": "object",
      "properties": {
        "1": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "2": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "3": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "restricted": {
      "type": "array",
      "items": {
        "minLength": 1,
        "type": "string"
      }
    },
    "name": {
      "minLength": 1,
      "type": "string"
    },
    "format": {
      "minLength": 1,
      "type": "string"
    },
    "point_limit": {
      "minimum": 1,
      "type": "integer"
    }
  },
  "required": ["id", "name", "date_start", "format"]
}

=== AlexRodwell/netrunner-cards-json/v2/restrictions/standard/napd_mwl_1_2.json
{
  "id": "napd_mwl_1_2",
  "name": "NAPD MWL 1.2",
  "date_start": "2017-04-12",
  "format": "standard",
  "universal_faction_cost": {
    "1": [
      "parasite",
      "yog_0",
      "wyldside",
      "breaking_news",
      "sansan_city_grid",
      "clone_chip",
      "napd_contract",
      "d4v1d",
      "architect",
      "cerberus_lady_h1",
      "mumba_temple",
      "bio_ethics_association",
      "mumbad_city_hall",
      "temujin_contract"
    ],
    "3": [
      "blackmail",
      "faust",
      "ddos",
      "sensie_actors_union",
      "rumor_mill",
      "sifr"
    ]
  }
}
